version: '3'
services:
  web:
    depends_on:
      - db
    build: '.'
    environment:
      - SINGLEVIEW_HOST=db
      - SINGLEVIEW_PORT=5432
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
  db:
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - ~/docker/volumes/postgres:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      POSTGRES_USER: 'singleview_user'
      POSTGRES_PASSWORD: ''
      POSTGRES_DB: hnsingleview
