version: '3'
services:
  db:
    image: postgres
    ports:
      - '10101:5432'
    volumes:
      - ~/docker/volumes/postgres:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      POSTGRES_USER: 'singleview_user'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: hnsingleview

  sql_test_db:
    image: 'mcr.microsoft.com/mssql/server'
    ports:
      - '1433:1433'
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/api/test/sql/UHT/schema.sql
    environment:
      SA_PASSWORD: 'UHT_password'
      ACCEPT_EULA: 'Y'
