version: '3'
services:
  db:
    image: postgres:12
    ports:
      - '10101:5432'
    volumes:
      - ~/docker/volumes/postgres:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: 'singleview_user'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: hnsingleview

  test_db:
    container_name: test_db
    image: postgres:12
    ports:
      - '10102:5432'
    volumes:
      - ~/docker/volumes/postgres2:/var/lib/postgresql/data2
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      TZ: Europe/London
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: 'singleview_user'
      POSTGRES_DB: hnsingleview

  external_test_dbs:
    container_name: external_test_dbs
    image: mcr.microsoft.com/mssql/server:2019-latest
    build:
      context: .
      dockerfile: ./dockerfiles/externalDB/Dockerfile
    ports:
      - 1433:1433
    environment:
      TZ: Europe/London

  test_api:
    container_name: test_api
    image: test_api
    build:
      context: .
      dockerfile: ./dockerfiles/testAPI/Dockerfile
    ports:
      - 3010:3010
    depends_on:
      - test_db
      - external_test_dbs
    environment:
      TZ: Europe/London
