version: '3'
services:
  db:
    image: postgres
    ports:
      - '10101:5432'
    volumes:
      - ~/docker/volumes/postgres:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      POSTGRES_USER: 'singleview_user'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: hnsingleview

  uh_test_db:
    image: 'mcr.microsoft.com/mssql/server'
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 1433:1433
