version: "3"
services:
  web:
    depends_on:
      - db
    build: "."
    ports:
      - "3010:3010"
    volumes:
      - .:/usr/src/app
  db:
    image: postgres
    ports:
      - "10101:5432"
    volumes:
      - ~/docker/volumes/postgres:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      POSTGRES_USER: "singleview_user"
      POSTGRES_PASSWORD: ""
      POSTGRES_DB: singleview_prod
