service: hn-single-view-api

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-2
  stage: production
  profile: hackney
  timeout: 15
  vpc:
    securityGroupIds:
      - sg-022acccbebd7bca46
    subnetIds:
      - subnet-00356e0650138f74f
      - subnet-0a7f442c22a6feedc

plugins:
  - serverless-offline
  - serverless-offline-ssm

functions:
  hn-single-view-api:
    name: hn-single-view-api-${self:provider.stage}
    role: arn:aws:iam::775052747630:role/LBH_Lambda_Execution
    handler: api/index.handler
    package:
      exclude:
        - '**'
      include:
        - api/index.js
        - api/lib/**
        - api/node_modules/**
    events:
      - http:
          path: '{proxy+}'
          method: ANY
          authorizer: ${self:custom.authorizer.hn-single-view-api-authorizer}
    environment:
      UHT_user: ${ssm:/hn-single-view-api/production/UHT_user}
      UHT_password: ${ssm:/hn-single-view-api/production/UHT_password}
      UHT_server: ${ssm:/hn-single-view-api/production/UHT_server}
      UHT_database: ${ssm:/hn-single-view-api/production/UHT_database}
      UHW_user: ${ssm:/hn-single-view-api/production/UHW_user}
      UHW_password: ${ssm:/hn-single-view-api/production/UHW_password}
      UHW_server: ${ssm:/hn-single-view-api/production/UHW_server}
      UHW_database: ${ssm:/hn-single-view-api/production/UHW_database}
      Academy_user: ${ssm:/hn-single-view-api/production/Academy_user}
      Academy_password: ${ssm:/hn-single-view-api/production/Academy_password}
      Academy_server: ${ssm:/hn-single-view-api/production/Academy_server}
      Academy_database: ${ssm:/hn-single-view-api/production/Academy_database}
  hn-single-view-api-authorizer:
    name: hn-single-view-api-authorizer-${self:provider.stage}
    role: arn:aws:iam::775052747630:role/LBH_Lambda_Execution
    handler: authorizer/index.handler
    package:
      exclude:
        - '**'
      include:
        - authorizer/index.js
        - authorizer/node_modules/**
    environment:
      jwtsecret: ${ssm:/common/hackney-jwt-secret}
      allowedGroups: 'housingneeds-singleview-beta'

custom:
  stage: production
  authorizer:
    hn-single-view-api-authorizer:
      name: hn-single-view-api-authorizer
      type: request
      resultTtlInSeconds: 0
