service: hn-single-view-api

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-2
  stage: ${opt:stage}
  profile: hackney
  timeout: 15
  vpc:
    securityGroupIds:
      - sg-022acccbebd7bca46
    subnetIds:
      - subnet-00356e0650138f74f
      - subnet-0a7f442c22a6feedc

plugins:
  - serverless-offline
  - serverless-offline-ssm

functions:
  hn-single-view-api:
    name: hn-single-view-api-${self:provider.stage}
    role: arn:aws:iam::775052747630:role/LBH_Lambda_Execution
    handler: api/index.handler
    package:
      exclude:
        - '**'
      include:
        - api/index.js
        - api/lib/**
        - api/node_modules/**
    events:
      - http:
          path: '{proxy+}'
          method: ANY
          authorizer: ${self:custom.authorizer.hn-single-view-api-authorizer}
          cors:
            origins:
              - '*'
    environment:
      Jigsaw_email: ${ssm:/hn-single-view-api/production/Jigsaw_email}
      Jigsaw_password: ${ssm:/hn-single-view-api/production/Jigsaw_password}
      UHW_DB: ${ssm:/hn-single-view-api/production/UHW_DB}
      UHT_DB: ${ssm:/hn-single-view-api/production/UHT_DB}
      ACADEMY_DB: ${ssm:/hn-single-view-api/production/ACADEMY_DB}
      COLLAB_CASEWORK_API: https://hn-collab-tools-proto.herokuapp.com
      SINGLEVIEW_DB: ${ssm:/hn-single-view-api/${self:provider.stage}/SINGLEVIEW_DB}
      HN_COMINO_URL: ${ssm:/hn-single-view-api/production/HN_COMINO_URL}
      ENV: ${self:provider.stage}
      SENTRY_DSN: ${ssm:/hn-single-view-api/SENTRY_DSN}
      ENABLE_CACHING: false

  getJigsawDoc:
    name: hn-single-view-getJigsawDoc-${self:provider.stage}
    role: arn:aws:iam::775052747630:role/LBH_Lambda_Execution
    handler: api/index.getJigsawDoc
    package:
      exclude:
        - '**'
      include:
        - api/index.js
        - api/lib/**
        - api/node_modules/**
    events:
      - http:
          path: 'jigsaw/customers/{customerId}/documents/jigsaw/{jigsawDocId}'
          method: GET
          authorizer: ${self:custom.authorizer.hn-single-view-api-authorizer}
          cors:
            origins:
              - '*'
    environment:
      URL_PREFIX: 'jigsaw'
      Jigsaw_email: ${ssm:/hn-single-view-api/production/Jigsaw_email}
      Jigsaw_password: ${ssm:/hn-single-view-api/production/Jigsaw_password}
      UHW_DB: ${ssm:/hn-single-view-api/production/UHW_DB}
      UHT_DB: ${ssm:/hn-single-view-api/production/UHT_DB}
      ACADEMY_DB: ${ssm:/hn-single-view-api/production/ACADEMY_DB}
      COLLAB_CASEWORK_API: https://hn-collab-tools-proto.herokuapp.com
      SINGLEVIEW_DB: ${ssm:/hn-single-view-api/${self:provider.stage}/SINGLEVIEW_DB}
      HN_COMINO_URL: ${ssm:/hn-single-view-api/production/HN_COMINO_URL}
      ENV: ${self:provider.stage}
      SENTRY_DSN: ${ssm:/hn-single-view-api/SENTRY_DSN}
      ENABLE_CACHING: false

  hn-single-view-api-authorizer:
    name: hn-single-view-api-authorizer-${self:provider.stage}
    role: arn:aws:iam::775052747630:role/LBH_Lambda_Execution
    handler: authorizer/index.handler
    package:
      exclude:
        - '**'
      include:
        - authorizer/index.js
        - authorizer/node_modules/**
    environment:
      jwtsecret: ${ssm:/common/hackney-jwt-secret}
      allowedGroups: 'housingneeds-singleview-beta'
      ENV: ${self:provider.stage}
      SENTRY_DSN: ${ssm:/hn-single-view-api/SENTRY_DSN}

resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'

custom:
  stage: ${self:provider.stage}
  authorizer:
    hn-single-view-api-authorizer:
      name: hn-single-view-api-authorizer
      type: request
      resultTtlInSeconds: 0
