service: hn-single-view-api

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-2
  stage: ${opt:stage}
  profile: hackney
  timeout: 15
  vpc:
    securityGroupIds:
      - sg-022acccbebd7bca46
    subnetIds:
      - subnet-00356e0650138f74f
      - subnet-0a7f442c22a6feedc

plugins:
  - serverless-offline
  - serverless-offline-ssm

package:
  individually: true
  exclude:
    - ./**

functions:
  hn-single-view-api:
    name: hn-single-view-api-${self:provider.stage}
    role: arn:aws:iam::775052747630:role/LBH_Lambda_Execution
    handler: api/index.handler
    package:
      include:
        - api/index.js
        - api/lib/**
        - jigsaw/**
        - api/node_modules/**
    events:
      - http:
          path: '{proxy+}'
          method: ANY
          authorizer: ${self:custom.authorizer.hn-single-view-api-authorizer}
          cors:
            origins:
              - '*'
    environment:
      Jigsaw_email: ${ssm:/hn-single-view-api/${self:provider.stage}/Jigsaw_email}
      Jigsaw_password: ${ssm:/hn-single-view-api/${self:provider.stage}/Jigsaw_password}
      JigsawLoginUrl: ${ssm:/hn-single-view-api/${self:provider.stage}/JigsawLoginUrl}
      JigsawCustomerBaseSearchUrl: ${ssm:/hn-single-view-api/${self:provider.stage}/JigsawCustomerBaseSearchUrl}
      JigsawHomelessnessBaseSearchUrl: ${ssm:/hn-single-view-api/${self:provider.stage}/JigsawHomelessnessBaseSearchUrl}
      JigsawAccommodationBaseSearchUrl: ${ssm:/hn-single-view-api/${self:provider.stage}/JigsawAccommodationBaseSearchUrl}
      UHW_DB: ${ssm:/hn-single-view-api/${self:provider.stage}/UHW_DB}
      UHT_DB: ${ssm:/hn-single-view-api/${self:provider.stage}/UHT_DB}
      ACADEMY_DB: ${ssm:/hn-single-view-api/${self:provider.stage}/ACADEMY_DB}
      COLLAB_CASEWORK_API: ${ssm:/hn-single-view-api/${self:provider.stage}/COLLAB_CASEWORK_API}
      SINGLEVIEW_DB: ${ssm:/hn-single-view-api/${self:provider.stage}/SINGLEVIEW_DB}
      HN_COMINO_URL: ${ssm:/hn-single-view-api/${self:provider.stage}/HN_COMINO_URL}
      W2_DOCUMENTS_API: ${ssm:/hn-single-view-api/${self:provider.stage}/W2_DOCUMENTS_API}
      JIGSAW_DOCUMENTS_API: ${ssm:/hn-single-view-api/${self:provider.stage}/JIGSAW_DOCUMENTS_API}
      ENV: ${self:provider.stage}
      SENTRY_DSN: ${ssm:/hn-single-view-api/SENTRY_DSN}
      SHARED_PLAN_BASE_URL: ${ssm:/hn-single-view-api/${self:provider.stage}/SHARED_PLAN_BASE_URL}
      VULNERABILITIES_BASE_URL: ${ssm:/hn-single-view-api/${self:provider.stage}/VULNERABILITIES_BASE_URL}
      ACADEMY_API_BASE_URL: ${ssm:/hn-single-view-api/${self:provider.stage}/ACADEMY_API_BASE_URL}
      ACADEMY_API_API_TOKEN: ${ssm:/hn-single-view-api/${self:provider.stage}/ACADEMY_API_API_TOKEN}
      HOUSING_API_BASE_URL: ${ssm:/hn-single-view-api/${self:provider.stage}/HOUSING_API_BASE_URL}
      HOUSING_API_TOKEN: ${ssm:/hn-single-view-api/${self:provider.stage}/HOUSING_API_TOKEN}
      HOUSING_API_API_KEY: ${ssm:/hn-single-view-api/${self:provider.stage}/HOUSING_API_API_KEY}
      CAUTIONARY_ALERTS_BASE_URL: ${ssm:/hn-single-view-api/${self:provider.stage}/CAUTIONARY_ALERTS_BASE_URL}
      CAUTIONARY_ALERTS_API_TOKEN: ${ssm:/hn-single-view-api/${self:provider.stage}/CAUTIONARY_ALERTS_API_TOKEN}
      TENANCY_API_BASE_URL: ${ssm:/hn-single-view-api/${self:provider.stage}/TENANCY_API_BASE_URL}
      TENANCY_API_TOKEN: ${ssm:/hn-single-view-api/${self:provider.stage}/TENANCY_API_TOKEN}
      MAT_SERVICE_API_BASE_URL: ${ssm:/hn-single-view-api/${self:provider.stage}/MAT_SERVICE_API_BASE_URL}
      MAT_SERVICE_API_TOKEN: ${ssm:/hn-single-view-api/${self:provider.stage}/MAT_SERVICE_API_TOKEN}
      MRA_API_BASE_URL: ${ssm:/hn-single-view-api/${self:provider.stage}/MRA_API_BASE_URL}
      MRA_API_TOKEN: ${ssm:/hn-single-view-api/${self:provider.stage}/MRA_API_TOKEN}~true

  hn-single-view-api-authorizer:
    name: hn-single-view-api-authorizer-${self:provider.stage}
    role: arn:aws:iam::775052747630:role/LBH_Lambda_Execution
    handler: authorizer.handler
    package:
      include:
        - authorizer.js
        - node_modules/**
    environment:
      jwtsecret: ${ssm:/common/hackney-jwt-secret}
      allowedGroups:
        'Fn::Join':
          - ','
          - ${self:custom.allowedGroups.${self:provider.stage}}
      ENV: ${self:provider.stage}
      SENTRY_DSN: ${ssm:/hn-single-view-api/SENTRY_DSN}

resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'

custom:
  stage: ${self:provider.stage}
  allowedGroups:
    staging:
      - contact-centre-staging
      - benefit-counter-staging
      - housing-counter-staging
      - housing-officer-staging
      - area-housing-manager-staging
      - housing-needs-staging
      - housingneeds-singleview-beta
      - development-team-staging
    production:
      - contact-centre-production
      - benefit-counter-production
      - housing-counter-production
      - housing-officer-production
      - area-housing-manager-production
      - housing-needs-production
      - housingneeds-singleview-beta
      - development-team-production
  authorizer:
    hn-single-view-api-authorizer:
      name: hn-single-view-api-authorizer
      type: request
      identitySource: ''
      resultTtlInSeconds: 0
