version: 2.1

executors:
  my-executor:
    docker:
      - image: circleci/node:12.13

    working_directory: ~/repo

jobs:
  build:
    executor: my-executor

    steps:
      - checkout

      - run:
          name: Concatenate all package-lock.json files into single file for checksum
          command: cat package.json api/package.json authorizer/package.json > combined-package-lock.txt

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}-{{ checksum "combined-package-lock.txt" }}
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: |
            sudo npm i && pushd api && npm i && popd && pushd authorizer && npm i && popd

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}-{{ checksum "combined-package-lock.txt" }}

      - persist_to_workspace:
          root: ~/repo
          paths: .

  test:
    executor: my-executor
    machine: true
    steps:
      - attach_workspace:
          at: ~/repo

      - run:
          shell: /bin/sh
          command: |
            export Jigsaw_email=${JIGSAW_EMAIL_DEV}
            export Jigsaw_password=${JIGSAW_PASSWORD_DEV}
            export UHW_DB=${UHW_DEV}
            export UHT_DB=${UHT_DEV}
            export ACADEMY_DB=${ACADEMY_DEV}
            export SINGLEVIEW_DB=${SINGLEVIEW_DEV}
            export HN_COMINO_URL=${COMINO_DEV}
            echo "ENV=dev\nPORT=3000\n/hn-single-view-api/dev/Jigsaw_email=x\n/hn-single-view-api/dev/Jigsaw_password=$JIGSAW_PASSWORD_DEV\n/hn-single-view-api/dev/UHW_DB=$UHW_DEV\n/hn-single-view-api/dev/UHT_DB=$UHT_DEV\n/hn-single-view-api/dev/ACADEMY_DB=$ACADEMY_DEV\n/hn-single-view-api/dev/SINGLEVIEW_DB=$SINGLEVIEW_DEV\n/hn-single-view-api/dev/HN_COMINO_URL=$COMINO_DEV\n/hn-single-view-api/SENTRY_DSN=x\n/common/hackney-jwt-secret=x" >> .env
            cat .env

      - run:
          name: Run linter
          command: npm run lint

      - run:
          name: Run tests with coverage
          command: |
            npm run test-ci

  deploy-staging:
    executor: my-executor

    steps:
      - attach_workspace:
          at: ~/repo

      - run:
          name: Install Serverless CLI
          command: |
            sudo npm i -g serverless

      - run:
          name: Set AWS credentials
          command: |
            pushd ~ && serverless config credentials -p aws -k $AWS_ACCESS_KEY_ID -s $AWS_SECRET_ACCESS_KEY -n hackney && popd

      - run:
          name: Deploy application
          command: sls deploy -s staging

  deploy-production:
    executor: my-executor

    steps:
      - attach_workspace:
          at: ~/repo

      - run:
          name: Install Serverless CLI
          command: |
            sudo npm i -g serverless

      - run:
          name: Set AWS credentials
          command: |
            pushd ~ && serverless config credentials -p aws -k ${AWS_ACCESS_KEY_ID} -s ${AWS_SECRET_ACCESS_KEY} -n hackney && popd

      - run:
          name: Deploy application
          command: sls deploy -s production

workflows:
  version: 2
  continuous-delivery:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy-staging:
          requires:
            - test
          filters:
            branches:
              only:
                - master
      - permit-deploy-production:
          type: approval
          requires:
            - deploy-staging
      - deploy-production:
          requires:
            - permit-deploy-production
